
# Generated by CodiumAI
from memory_cards import MemoryCards


import pytest


class TestMemoryCards:

    def test_create_memory_cards_instance(self):
        suit = "Corazones"
        value = "As"
        memory_card = MemoryCards(suit, value)

        assert memory_card.suit == suit
        assert memory_card.value == value

    # Flip a MemoryCards instance
    def test_flip_memory_card_instance(self):
        suit = "Corazones"
        value = "As"
        memory_card = MemoryCards(suit, value)

        assert not memory_card.flipped
        memory_card.flip()
        assert memory_card.flipped
